### ISSUE TITLE
Document title to appear as name in module

### ISSUE THREAD

**Issue by mckenziewest** [ofloveandhate/markdown2canvas#14]
I'd like for custom document names in module entries so that students don't have to see my naming conventions.

**Comment by ofloveandhate** [comment]
Is this for `File`s?  so, you want to be able to apply arbitrary names to files listed in modules?

**Comment by ofloveandhate** [comment]
oh nice, you're on it!   🥇

**Comment by ofloveandhate** [comment]
bam!
